### ISSUE TITLE
activation error Blender 3.0.0

### ISSUE THREAD

**Issue by Sinasta** [s-leger/blender_cad_transforms#57]
This is the Error i get upon activation on blender 3.0.0

CAD Transform 0.91.0 : error while loading
register_class(...): already registered as a subclass 'SLCAD_keymap'
Exception in module register(): /home/sinasta/.config/blender/3.0/scripts/addons/slcad_transform/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/sinasta/.config/blender/3.0/scripts/addons/slcad_transform/slcad_transform.py", line 3728, in register
    register_class(SLCAD_keymap)
ValueError: register_class(...): already registered as a subclass 'SLCAD_keymap'

**Comment by s-leger** [comment]
Hi Sinasta,
Will not provide any support for 3.0 until release, as things may break every days. Current release is likely to fail due to a change in api done for 2.93+
That being said, looks like you are re-installing another release without restarting blender in the between, leading in such errors.
